### ISSUE TITLE
mvn clean install fail

### ISSUE THREAD

**Issue by okdzhimiev** [jcuda/jcuda-main#33]
Log:
```
$ cd jcuda-main
$ mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] JCuda
[INFO] jcuda-common
[INFO] jcuda-natives
[INFO] jcuda
[INFO] jcublas-natives
[INFO] jcublas
[INFO] jcufft-natives
[INFO] jcufft
[INFO] jcurand-natives
[INFO] jcurand
[INFO] jcusparse-natives
[INFO] jcusparse
[INFO] jcusolver-natives
[INFO] jcusolver
[INFO] jnvgraph-natives
[INFO] jnvgraph
[INFO] jcudnn-natives
[INFO] jcudnn
[INFO] jcuda-main
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JCuda 10.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jcuda-parent ---
[INFO] 
[INFO] >>> maven-source-plugin:2.1.2:jar (attach-sources) > generate-sources @ jcuda-parent >>>
[INFO] 
[INFO] <<< maven-source-plugin:2.1.2:jar (attach-sources) < generate-sources @ jcuda-parent <<<
[INFO] 
[INFO] --- maven-source-plugin:2.1.2:jar (attach-sources) @ jcuda-parent ---
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.1:jar (attach-javadocs) @ jcuda-parent ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ jcuda-parent ---
[INFO] Installing /home/oleg/GIT/test/jcuda/jcuda-parent/pom.xml to /home/oleg/.m2/repository/org/jcuda/jcuda-parent/10.0.0/jcuda-parent-10.0.0.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building jcuda-common 10.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jcuda-common ---
[INFO] Deleting /home/oleg/GIT/test/jcuda/jcuda-common/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jcuda-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/oleg/GIT/test/jcuda/jcuda-common/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ jcuda-common ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jcuda-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/oleg/GIT/test/jcuda/jcuda-common/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ jcuda-common ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ jcuda-common ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ jcuda-common ---
[INFO] Building jar: /home/oleg/GIT/test/jcuda/jcuda-common/target/jcuda-common-10.0.0.jar
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (create-native-sources-jar) @ jcuda-common ---
[INFO] Building jar: /home/oleg/GIT/test/jcuda/jcuda-common/target/jcuda-common-10.0.0-sources.jar
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (create-native-javadoc-jar) @ jcuda-common ---
[INFO] Building jar: /home/oleg/GIT/test/jcuda/jcuda-common/target/jcuda-common-10.0.0-javadoc.jar
[INFO] 
[INFO] >>> maven-source-plugin:2.1.2:jar (attach-sources) > generate-sources @ jcuda-common >>>
[INFO] 
[INFO] <<< maven-source-plugin:2.1.2:jar (attach-sources) < generate-sources @ jcuda-common <<<
[INFO] 
[INFO] --- maven-source-plugin:2.1.2:jar (attach-sources) @ jcuda-common ---
[INFO] No sources in project. Archive not created.
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.1:jar (attach-javadocs) @ jcuda-common ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ jcuda-common ---
[INFO] Installing /home/oleg/GIT/test/jcuda/jcuda-common/target/jcuda-common-10.0.0.jar to /home/oleg/.m2/repository/org/jcuda/jcuda-common/10.0.0/jcuda-common-10.0.0.jar
[INFO] Installing /home/oleg/GIT/test/jcuda/jcuda-common/pom.xml to /home/oleg/.m2/repository/org/jcuda/jcuda-common/10.0.0/jcuda-common-10.0.0.pom
[INFO] Installing /home/oleg/GIT/test/jcuda/jcuda-common/target/jcuda-common-10.0.0-sources.jar to /home/oleg/.m2/repository/org/jcuda/jcuda-common/10.0.0/jcuda-common-10.0.0-sources.jar
[INFO] Installing /home/oleg/GIT/test/jcuda/jcuda-common/target/jcuda-common-10.0.0-javadoc.jar to /home/oleg/.m2/repository/org/jcuda/jcuda-common/10.0.0/jcuda-common-10.0.0-javadoc.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building jcuda-natives 10.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jcuda-natives ---
[INFO] Deleting /home/oleg/GIT/test/jcuda/jcuda/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jcuda-natives ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/oleg/GIT/test/jcuda/jcuda/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ jcuda-natives ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jcuda-natives ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/oleg/GIT/test/jcuda/jcuda/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ jcuda-natives ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ jcuda-natives ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ jcuda-natives ---
[INFO] Building jar: /home/oleg/GIT/test/jcuda/jcuda/target/jcuda-natives-10.0.0.jar
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (create-native-jar) @ jcuda-natives ---
[INFO] Building jar: /home/oleg/GIT/test/jcuda/jcuda/target/jcuda-natives-10.0.0-linux-x86_64.jar
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (create-native-sources-jar) @ jcuda-natives ---
[INFO] Building jar: /home/oleg/GIT/test/jcuda/jcuda/target/jcuda-natives-10.0.0-sources.jar
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (create-native-javadoc-jar) @ jcuda-natives ---
[INFO] Building jar: /home/oleg/GIT/test/jcuda/jcuda/target/jcuda-natives-10.0.0-javadoc.jar
[INFO] 
[INFO] >>> maven-source-plugin:2.1.2:jar (attach-sources) > generate-sources @ jcuda-natives >>>
[INFO] 
[INFO] <<< maven-source-plugin:2.1.2:jar (attach-sources) < generate-sources @ jcuda-natives <<<
[INFO] 
[INFO] --- maven-source-plugin:2.1.2:jar (attach-sources) @ jcuda-natives ---
[INFO] No sources in project. Archive not created.
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.1:jar (attach-javadocs) @ jcuda-natives ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ jcuda-natives ---
[INFO] Installing /home/oleg/GIT/test/jcuda/jcuda/target/jcuda-natives-10.0.0.jar to /home/oleg/.m2/repository/org/jcuda/jcuda-natives/10.0.0/jcuda-natives-10.0.0.jar
[INFO] Installing /home/oleg/GIT/test/jcuda/jcuda/pom.xml to /home/oleg/.m2/repository/org/jcuda/jcuda-natives/10.0.0/jcuda-natives-10.0.0.pom
[INFO] Installing /home/oleg/GIT/test/jcuda/jcuda/target/jcuda-natives-10.0.0-linux-x86_64.jar to /home/oleg/.m2/repository/org/jcuda/jcuda-natives/10.0.0/jcuda-natives-10.0.0-linux-x86_64.jar
[INFO] Installing /home/oleg/GIT/test/jcuda/jcuda/target/jcuda-natives-10.0.0-sources.jar to /home/oleg/.m2/repository/org/jcuda/jcuda-natives/10.0.0/jcuda-natives-10.0.0-sources.jar
[INFO] Installing /home/oleg/GIT/test/jcuda/jcuda/target/jcuda-natives-10.0.0-javadoc.jar to /home/oleg/.m2/repository/org/jcuda/jcuda-natives/10.0.0/jcuda-natives-10.0.0-javadoc.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building jcuda 10.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jcuda ---
[INFO] Deleting /home/oleg/GIT/test/jcuda/jcuda/JCudaJava/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jcuda ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/oleg/GIT/test/jcuda/jcuda/JCudaJava/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ jcuda ---
[INFO] Compiling 155 source files to /home/oleg/GIT/test/jcuda/jcuda/JCudaJava/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jcuda ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ jcuda ---
[INFO] Compiling 13 source files to /home/oleg/GIT/test/jcuda/jcuda/JCudaJava/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ jcuda ---
[INFO] Surefire report directory: /home/oleg/GIT/test/jcuda/jcuda/JCudaJava/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running jcuda.test.JCudaKernelParamsTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.175 sec <<< FAILURE! - in jcuda.test.JCudaKernelParamsTest
testKernelParams(jcuda.test.JCudaKernelParamsTest)  Time elapsed: 0.153 sec  <<< ERROR!
jcuda.CudaException: Could not create ptx file
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:621)
        at java.lang.Runtime.exec(Runtime.java:451)
        at java.lang.Runtime.exec(Runtime.java:348)
        at jcuda.test.JCudaTestUtils.invokeNvcc(JCudaTestUtils.java:110)
        at jcuda.test.JCudaTestUtils.preparePtxFile(JCudaTestUtils.java:39)
        at jcuda.test.JCudaAbstractKernelTest.initialize(JCudaAbstractKernelTest.java:51)
        at jcuda.test.JCudaKernelParamsTest.testKernelParams(JCudaKernelParamsTest.java:60)

Running jcuda.test.TestPointerToBuffer
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in jcuda.test.TestPointerToBuffer
Running jcuda.test.JCudaDriverMemRangeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.107 sec - in jcuda.test.JCudaDriverMemRangeTest
Running jcuda.test.TestPointerGetByteBuffer
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in jcuda.test.TestPointerGetByteBuffer
Running jcuda.test.JCudaDriverTextureTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE! - in jcuda.test.JCudaDriverTextureTest
testTextures(jcuda.test.JCudaDriverTextureTest)  Time elapsed: 0.001 sec  <<< ERROR!
jcuda.CudaException: Could not create ptx file
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:621)
        at java.lang.Runtime.exec(Runtime.java:451)
        at java.lang.Runtime.exec(Runtime.java:348)
        at jcuda.test.JCudaTestUtils.invokeNvcc(JCudaTestUtils.java:110)
        at jcuda.test.JCudaTestUtils.preparePtxFile(JCudaTestUtils.java:39)
        at jcuda.test.JCudaDriverTextureTest.testTextures(JCudaDriverTextureTest.java:114)

Running jcuda.test.JCudaBasicBindingTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.161 sec - in jcuda.test.JCudaBasicBindingTest
Running jcuda.test.JCudaPointersToPointerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.059 sec - in jcuda.test.JCudaPointersToPointerTest
Running jcuda.test.JCudaMemcpy3DTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in jcuda.test.JCudaMemcpy3DTest
Running jcuda.test.JCudaDriverTextureDescriptorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.094 sec - in jcuda.test.JCudaDriverTextureDescriptorTest
Running jcuda.test.JCudaDriverPrimaryContextTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in jcuda.test.JCudaDriverPrimaryContextTest

Results :

Tests in error: 
  JCudaKernelParamsTest.testKernelParams:60->JCudaAbstractKernelTest.initialize:51 » Cuda
  JCudaDriverTextureTest.testTextures:114 » Cuda Could not create ptx file

Tests run: 21, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JCuda .............................................. SUCCESS [  0.870 s]
[INFO] jcuda-common ....................................... SUCCESS [  0.619 s]
[INFO] jcuda-natives ...................................... SUCCESS [  0.145 s]
[INFO] jcuda .............................................. FAILURE [  2.841 s]
[INFO] jcublas-natives .................................... SKIPPED
[INFO] jcublas ............................................ SKIPPED
[INFO] jcufft-natives ..................................... SKIPPED
[INFO] jcufft ............................................. SKIPPED
[INFO] jcurand-natives .................................... SKIPPED
[INFO] jcurand ............................................ SKIPPED
[INFO] jcusparse-natives .................................. SKIPPED
[INFO] jcusparse .......................................... SKIPPED
[INFO] jcusolver-natives .................................. SKIPPED
[INFO] jcusolver .......................................... SKIPPED
[INFO] jnvgraph-natives ................................... SKIPPED
[INFO] jnvgraph ........................................... SKIPPED
[INFO] jcudnn-natives ..................................... SKIPPED
[INFO] jcudnn ............................................. SKIPPED
[INFO] jcuda-main ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.678 s
[INFO] Finished at: 2020-03-10T13:48:17-06:00
[INFO] Final Memory: 28M/474M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project jcuda: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/oleg/GIT/test/jcuda/jcuda/JCudaJava/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jcuda

```

**Comment by jcuda** [comment]
These particular tests are trying to compile a `.cu` file and generate a `.ptx` ("CUDA assembler") file which is then loaded, in order to execute the kernel. The compilation is done by invoking the NVCC (CUDA compiler).

(In "real" applications, this would usually not be necessary in this exact form: One would usually create the `.ptx` file beforehand, or use the runtime compiler....)

My first guess would be that it has something to do with access rights - i.e. the build process may not have the right permissions to call the NVCC or generate the file, at 

    jcuda.CudaException: Could not create ptx file
            at java.lang.UNIXProcess.forkAndExec(Native Method)

Maybe re-runing it with the `-e` switch to show the stack traces could bring some insights. Otherwise, I'd have to think about other possible solutions for that...

**Comment by okdzhimiev** [comment]
Found the problem - my _nvcc_ is at /usr/local/cuda/bin. 
Java's runtime PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin.

**Comment by jcuda** [comment]
I'm not so familiar with the details of the path lookups on Linux. It may not be "critical", and maybe it is not even really an issue with JCuda or the test. But I'll keep an eye on that (and leave the issue open for now), to see whether this is a general problem or just some glitch of the specific CUDA version, target system, or installation procedure.

**Comment by okdzhimiev** [comment]
It's not critical. Here's more details and a better solution:
Details:
- OS: Kubuntu 16.04
- CUDA drivers (9.2, 10.0, 10.1, 10.2) get installed into /usr/local/cuda-XX.X. The latest driver installed gets linked to /usr/local/cuda.

Solution:
```
# run once (preferably at time when you install CUDA drivers)
echo 'export PATH="$PATH:/usr/local/cuda/bin"' >> ~/.bashrc
source ~/.bashrc
```
Then normally run:
```
cd <somepath>/jcuda/jcuda-main
mvn clean install
```

**Comment by jcuda** [comment]
So this seemed to be some path configuration on the target system. Closing for now. Reopen if needed.
